name: pokedex
description: A Pokédex app using the PokéAPI.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.12.0+2
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - pokeball.png
   - pikachu.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
